# Authored by: Jason Lunder, Github: https://github.com/jlunder00/
model:
  # task_type: similarity
  # task_type: binary
  # task_type: infonce
  task_type: entailment
  task_loader_type: aggregative
  name: tree_matching
  model_type: matching
  node_feature_dim: 804
  edge_feature_dim: 70
  # node_state_dim: 1024
  # edge_state_dim: 256
  node_state_dim: 512
  edge_state_dim: 128
  #both edge and node hidden sizes will have a node_state_dim*2 or node_state_dim*3 layer appended in model definition. x3 or x2 is dependant on embedding vs matching type as is required
  edge_hidden_sizes: 
    - 256
  node_hidden_sizes: 
    - 512
  
  graph_rep_dim: 768
  #graph_transform_sizes wil have graph_rep_dim appended on it
  graph_transform_sizes: 
    - 512

  edge_net_init_scale: 0.1
  reverse_dir_param_different: false
  use_reverse_direction: true
  share_prop_params: true

  n_prop_layers: 1
  temperature: 0.05
  aggregation: attention

  # for patentmatch
  # positive_infonce_weight: 0.3
  # inverse_infonce_weight: 1.0
  # midpoint_infonce_weight: 0.0
  # thresh_low: 0.5
  # thresh_high: 0.5

  #for entailment and semeval
  positive_infonce_weight: 0.05
  inverse_infonce_weight: 1.0
  midpoint_infonce_weight: 0.1
  thresh_low: -0.33
  thresh_high: 0.33

  #for binary
  threshold: 0.0



data:
  # dataset_type: patentmatch_balanced
  # dataset_type: semeval
  dataset_type: snli

  batch_size: 16
  strict_matching: False
  min_trees_per_group: 1
  num_workers_train: 0
  num_workers_val: 0
  prefetch_factor: 0
  max_batches_per_epoch: 1000
  contrastive_mode: True
  allow_negatives: True
  allow_neutrals: True
  allow_positives: True

embedding_cache_dir: '/home/jlunder/research/TMN_DataGen/embedding_cache4/'
use_gpu: false

train:
  learning_rate: 0.000001
  weight_decay: 0.00001
  n_epochs: 500
  patience: 10
  gradient_accumulation_steps: 1
  clip_value: 1.0
  cleanup_interval: 5

wandb:
  project: tree-embedding
  # tags: [aggregative, patentmatch_balanced]
  # tags: [aggregative, semeval]
  tags: [aggregative, snli]
  log_interval: 10
  memory_logging: true

