
model:
  task_type: infonce
  task_loader_type: aggregative
  name: tree_matching
  model_type: matching
  node_feature_dim: 804
  edge_feature_dim: 70
  node_state_dim: 1024
  edge_state_dim: 256
  #both edge and node hidden sizes will have a node_state_dim*2 or node_state_dim*3 layer appended in model definition. x3 or x2 is dependant on embedding vs matching type as is required
  edge_hidden_sizes: 
    - 512
  node_hidden_sizes: 
    - 1024
  
  graph_rep_dim: 1792
  #graph_transform_sizes wil have graph_rep_dim appended on it
  graph_transform_sizes: 
    - 1024

  edge_net_init_scale: 0.1
  reverse_dir_param_different: false
  use_reverse_direction: true
  share_prop_params: true

  n_prop_layers: 5
  temperature: 0.05
  aggregation: attention


data:
  dataset_type: patentmatch_balanced

  batch_size: 512
  strict_matching: False
  min_trees_per_group: 1
  num_workers: 8
  prefetch_factor: 1
  max_batches_per_epoch: 1000
  contrastive_mode: True

embedding_cache_dir: '/home/jlunder/research/TMN_DataGen/embedding_cache4/'
use_gpu: false

train:
  learning_rate: 0.000001
  weight_decay: 0.00001
  n_epochs: 100
  patience: 10
  gradient_accumulation_steps: 1
  clip_value: 1.0
  cleanup_interval: 5

wandb:
  project: tree-embedding
  tags: [aggregative, patentmatch_balanced]
  log_interval: 10
  memory_logging: true

