# configs/experiment_configs/contrastive_config.yaml
model:
  task_type: info_nce
  task_loader_type: contrastive
  name: tree_matching
  node_feature_dim: 804
  edge_feature_dim: 22
  node_hidden_dim: 1024
  edge_hidden_dim: 512
  n_prop_layers: 5
  dropout: 0.2
  temperature: 0.07

data:
  dataset_type: wikiqs
  batch_size: 512
  pos_pairs_per_anchor: 4
  neg_pairs_per_anchor: 10
  min_groups_per_batch: 8
  anchors_per_group: 2
  num_workers: 12
  prefetch_factor: 2

train:
  learning_rate: 0.0005
  weight_decay: 0.00001
  n_epochs: 100
  patience: 10
  gradient_accumulation_steps: 1
  clip_value: 1.0
  cleanup_interval: 5

wandb:
  project: tree-matching
  tags: [contrastive, wikiqs]
  log_interval: 10
  memory_logging: true
