# configs/experiment_configs/contrastive_config.yaml
model:
  task_type: info_nce
  task_loader_type: contrastive
  name: tree_matching
  node_feature_dim: 804
  edge_feature_dim: 70
  node_hidden_dim: 1024
  edge_hidden_dim: 512
  n_prop_layers: 5
  dropout: 0.2
  temperature: 0.5

data:
  dataset_type: wikiqs
  batch_size: 750
  pos_pairs_per_anchor: 1
  neg_pairs_per_anchor: 10
  min_groups_per_batch: 8
  anchors_per_group: 1
  num_workers: 4
  prefetch_factor: 1

embedding_cache_dir: '/home/jlunder/research/TMN_DataGen/embedding_cache4/'
use_gpu: false

train:
  learning_rate: 0.00001
  weight_decay: 0.00001
  n_epochs: 100
  patience: 10
  gradient_accumulation_steps: 1
  clip_value: 1.0
  cleanup_interval: 5

wandb:
  project: tree-matching
  tags: [contrastive, wikiqs]
  log_interval: 10
  memory_logging: true
