# configs/experiment_configs/entailment_config.yaml
# model:
#   task_type: entailment
#   name: tree_matching
#   node_feature_dim: 804
#   edge_feature_dim: 22
#   node_hidden_dim: 256
#   edge_hidden_dim: 128
#   n_prop_layers: 5
#   dropout: 0.2
#   loss_params:
#     thresholds: [-0.3, 0.3]

model:
  task_type: entailment
  name: tree_matching
  node_feature_dim: 804
  edge_feature_dim: 22
  node_hidden_dim: 1024
  edge_hidden_dim: 512
  n_prop_layers: 5
  dropout: 0.2
  use_residuals: true
  layer_norm: true
  init_scale: 0.01
  gradient_checkpointing: true
  classifier_hidden_dim: 2048

data:
  dataset_type: snli
  batch_size: 512
  max_nodes_per_batch: 1000
  max_edges_per_batch: 2000
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true
  aggressive_cleanup: true

train:
  learning_rate: 0.0005 #5e-4
  weight_decay: 0.00001 #1e-5
  n_epochs: 160
  patience: 20
  gradient_accumulation_steps: 4
  clip_value: 1.0
  cleanup_interval: 5
  scheduler:
    cosine:
      T_0: 5
      T_mult: 2
      eta_min: 0.000001
    plateau:
      factor: 0.5
      patience: 5
      min_lr: 0.00001


wandb:
  project: tree-matching
  tags: [entailment]
  log_interval: 100
  memory_logging: true
