# configs/experiment_configs/similarity_config.yaml
model:
  task_type: similarity
  name: tree_matching
  node_feature_dim: 804
  # edge_feature_dim: 22 #semeval current
  edge_feature_dim: 70 #para50m current
  node_hidden_dim: 256
  edge_hidden_dim: 128
  n_prop_layers: 5
  dropout: 0.2
  loss_params:
    margin: 0.1

data:
  dataset_type: para50m
  batch_size: 1024
  max_nodes_per_batch: 1000
  max_edges_per_batch: 2000
  num_workers: 8
  prefetch_factor: 2

train:
  learning_rate: 0.0005 #5e-4
  weight_decay: 0.00001 #1e-5
  n_epochs: 500
  patience: 50
  gradient_accumulation_steps: 4
  clip_value: 1.0
  cleanup_interval: 5
  scheduler:
    cosine:
      T_0: 5
      T_mult: 2
      eta_min: 0.000001 #1e-6
    plateau:
      factor: 0.5
      patience: 50
      min_lr: 0.000001 #1e-6

wandb:
  project: tree-matching
  tags: [similarity, para50m]
  log_interval: 10
  memory_logging: true
