#configs/experiment_configs/tree_matching.yaml
MODEL:
  name: 'tree_matching'
  node_feature_dim: 768
  edge_feature_dim: 64
  node_hidden_dim: 256
  edge_hidden_dim: 128
  n_prop_layers: 5
  dropout: 0.1
  projection_dim: 128

DATA:
  train_path: 'data/snli_train.json'
  val_path: 'data/snli_val.json'
  test_path: 'data/snli_test.json'
  max_tree_size: 100
  batch_size: 32
  num_workers: 4

TRAIN:
  learning_rate: 0.0001
  weight_decay: 0.00001
  n_epochs: 100
  patience: 10
  warmup_steps: 1000
  gradient_clip: 1.0
  log_interval: 100

WANDB:
  project_name: 'tree-matching'
  entity: 'your-entity'
  tags: ['tree-matching', 'entailment']
